services:
  - type: web
    name: vini-civilwise-webapp-server
    env: node
    rootDir: server
    buildCommand: npm install && tsc
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
